# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Generate READMEs

on: [pull_request_target]
env:
  DENO_DIR: deno_cache

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('lock.json') }}
          path: ${{ env.DENO_DIR }}
      - name: Update authors.yml
        run: deno run --allow-read --allow-write --allow-net generateAuthors.ts --base ${{ github.event.pull_request.base.repo.full_name }} --num ${{ github.event.pull_request.number }} --name ${{ github.event.pull_request.user.login }}
      - name: Update READMEs
        run: deno run --allow-read --allow-write generate.tsx
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: re-generate READMEs"
